name: Build site

on:
  push:
    branches:
      - "master"
  pull_request:
  repository_dispatch:
    types: [update]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run demo
        env:
          NODE_ENV: "production"
      - name: GitHub Pages Deploy
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/dist
